version: '3.8'

services:
  # Servicio 1: Tu aplicación Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lego-api
    container_name: lego_app
    restart: unless-stopped
    ports:
      - "8080:8080" # Tu API estará en http://localhost:8080
    environment:
      # Aquí sobreescribimos el .env de Laravel para que hable con el contenedor 'db'
      DB_CONNECTION: mysql
      DB_HOST: db           # 'db' es el nombre del servicio de abajo
      DB_PORT: 3306
      DB_DATABASE: lego_db
      DB_USERNAME: lego_user
      DB_PASSWORD: secret_password
    depends_on:
      - db # Espera a que la base de datos arranque

  # Servicio 2: Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: lego_db
    restart: always
    environment:
      MYSQL_DATABASE: lego_db
      MYSQL_USER: lego_user
      MYSQL_PASSWORD: secret_password
      MYSQL_ROOT_PASSWORD: root_super_secret
    volumes:
      - db_data:/var/lib/mysql # Esto guarda los datos aunque apagues el contenedor
    ports:
      - "3307:3306" # Opcional: Para que puedas entrar con DBeaver/Workbench desde fuera

volumes:
  db_data: